### ISSUE TITLE
The extension works only for english

### ISSUE THREAD

**Issue by christianbraeunlich** [mmilince/bc-maximizer#1]
Hi @mmilince,
first of all: great extension!!

As our clients usually don't work with the english language in the web client. Would like to see a more general approach that covers all languages by default. The current state of the extension doesn't support any other language. This is due to the fact that the selector of the title is hardcoded in english: 
https://github.com/mmilince/bc-maximizer/blob/6a0892a90e2f77eb308f14ed9fdb51feae38010b/src/content.js#L11

See PR https://github.com/mmilince/bc-maximizer/pull/2 for a suggested solution

Maybe I'm missing something here and it's a matter of configuration? Thanks in advance!

**Comment by Arthurvdv** [comment]
I've enthusiastic shared this extension with my colleagues to then discover that it only works in English 🙈

Is there any change that this PR will be accepted?

**Comment by mmilince** [comment]
Hi @Arthurvdv thanks for commenting and reminding me, I completely forgot about this issue being created. 
I will test it and publish a new version of the extension in the coming days. 

ps. thanks @christianbraeunlich for creating this issue and PR as well :)

**Comment by mmilince** [comment]
This should be solved now!
New version of the app is available on the Chrome store. The new version for the Edge is still in the process of verification, and it should be live soon.
